apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


nameSuffix: -hml

namespace: flask-hml

resources:
- route.yaml
- hpa.yaml
- ns.yaml
- rq-flask.yaml
- ../../base
- rolebinding.yaml
- sa.yaml

images:
- name: flaskimage
  newName: quay.io/lagomes/flask-app
  newTag: v1
labels:
- includeSelectors: true
  pairs:
    env: flaskhml

patches:
- path: patch-deployment.yaml
