kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: flask
spec:
  flaskSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: 'flask-docker:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Dockerfile
#      from:
#        kind: ImageStreamTag
#        namespace: openshift
#        name: 'flask:latest'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/laurobmb/flask'
      ref: openshift
      contextDir: /
