apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: flask
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: alpine:latest
    referencePolicy:
      type: Source
